Update PRODManualValidation.yml

diff --git a/.github/workflows/PRODManualValidation.yml b/.github/workflows/PRODManualValidation.yml
--- a/.github/workflows/PRODManualValidation.yml
+++ b/.github/workflows/PRODManualValidation.yml
@@ -4,9 +4,16 @@ name: ValidatetoPROD
 # Controls when the workflow will run
 on:
    workflow_dispatch:
-   
+   inputs:
+     ValidateAgainstOrg:
+       description: 'Enter org to validate against'
+       required: true
+       type: choice
+       options:
+       - QA
+       - PROD
 jobs:
-    deploy-PROD:
+    deploy-QA:
         runs-on: ubuntu-latest
         steps:
         # Checkout the source code
@@ -38,3 +45,50 @@ jobs:
             # Deploy source to PROD org
             - name: 'Push source to PROD org'
               run: sfdx force:source:deploy -u chandrahasapreddy@kpmg.com.devopqa --testlevel RunLocalTests -c -p force-app/main/default
+
+name: ValidatetoQA
+# Controls when the workflow will run
+on:
+   workflow_dispatch:
+   inputs:
+     ValidateAgainstOrg:
+       description: 'Enter org to validate against'
+       required: true
+       type: choice
+       options:
+       - QA
+       - PROD
+
+   jobs:
+    deploy-PROD:
+        runs-on: ubuntu-latest
+        steps:
+        # Checkout the source code
+            - name: 'Checkout source code'
+              uses: actions/checkout@v2
+        # Install Salesforce CLI
+            - name: 'Install Salesforce CLI'
+              run: |
+                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
+                  mkdir ~/sfdx
+                  tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
+                  echo "$HOME/sfdx/bin" >> $GITHUB_PATH
+                  ~/sfdx/bin/sfdx version
+                  
+        # Store secret for acc org
+            - name: 'Populate auth file with SFDX_PROD_URL secret'
+              shell: bash
+              run: |
+                  echo ${{ secrets.SFDX_PROD_URL}} > ./SFDX_PROD_URL.txt
+                  secretFileSize=$(wc -c "./SFDX_PROD_URL.txt" | awk '{print $1}')
+                  if [ $secretFileSize == 1 ]; then
+                      echo "Missing SFDX_PROD_URL secret. Is this workflow running on a fork?";
+                      exit 1;
+                  fi
+            # Authenticate PROD
+            - name: 'Authenticate PROD'
+              run: sfdx auth:sfdxurl:store -f ./SFDX_PROD_URL.txt -a meeraacc -d
+              
+            # Deploy source to PROD org
+            - name: 'Push source to PROD org'
+              run: sfdx force:source:deploy -u pottennagari.chandra@salesforce.com --testlevel RunLocalTests -c -p force-app/main/default
