Update validation.yml

diff --git a/.github/workflows/validation.yml b/.github/workflows/validation.yml
--- a/.github/workflows/validation.yml
+++ b/.github/workflows/validation.yml
@@ -1,28 +1,43 @@
-name: Validate pull request
+# This is a basic workflow to help you get started with Actions
 
+name: DeploytoProd
+# Controls when the workflow will run
 on:
-  pull_request:
+   pull_request:
     branches:
       - QA
     types: [opened, edited, reopened, synchronize]
-    paths:
-      - 'force-app/**'
-
+   # Jobs to be executed
 jobs:
-  validate-deployment:
-    runs-on: ubuntu-latest
-    container:
-      image: salesforce/cli:latest-slim
-    steps:      
-      - name: 'Checkout source code'
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      
-      - name: 'Authenticate using SFDX_AUTH_URL'
-        run: | 
-          echo ${{ secrets.SFDX_AUTH_URL }} | sf org login sfdx-url -s -u
-
-      - name: 'Validate'
-        run: |
-          sf project deploy validate -d force-app/ -l RunLocalTests -w 10      
+    deploy-acc:
+        runs-on: ubuntu-latest
+        steps:
+        # Checkout the source code
+            - name: 'Checkout source code'
+              uses: actions/checkout@v2
+        # Install Salesforce CLI
+            - name: 'Install Salesforce CLI'
+              run: |
+                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
+                  mkdir ~/sfdx
+                  tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
+                  echo "$HOME/sfdx/bin" >> $GITHUB_PATH
+                  ~/sfdx/bin/sfdx version
+                  
+        # Store secret for acc org
+            - name: 'Populate auth file with SFDX_AUTH_URL secret'
+              shell: bash
+              run: |
+                  echo ${{ secrets.SFDX_AUTH_URL}} > ./SFDX_AUTH_URL.txt
+                  secretFileSize=$(wc -c "./SFDX_AUTH_URL.txt" | awk '{print $1}')
+                  if [ $secretFileSize == 1 ]; then
+                      echo "Missing SFDX_AUTH_URL secret. Is this workflow running on a fork?";
+                      exit 1;
+                  fi
+            # Authenticate acc
+            - name: 'Authenticate Acc'
+              run: sfdx auth:sfdxurl:store -f ./SFDX_AUTH_URL.txt -a meeraacc -d
+              
+            # Deploy source to Acc org
+            - name: 'Push source to Acc org'
+              run: sfdx force:source:deploy -u chandrahasapreddy@kpmg.com.devopqa -c -p force-app/main/default
